### PR TITLE
fix: correct an import path

### PR DESCRIPTION
**Pull request by mutokrm**
😺

### CODE REVIEW

**Review by OldBigBuddha — APPROVED** [review]
LGTM, Thanks your aggressive contribution!

**Comment by mutokrm** [comment]
Am I aggressive? 笑

**Comment by OldBigBuddha** [comment]
「積極的な」的な

**Comment by mutokrm** [comment]
The word aggressive can possibly make it sounds like I'm insulting or attacking you ...笑

**Comment by OldBigBuddha** [comment]
🙇‍♂️ :manabi:

**Pull request merged**
